In [10]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

file_path = r"C:\Users\jai ganesh\Documents\sla_analysis\data\delivery_order.csv"

df = pd.read_csv(file_path)

df.head()

,order_id,store_id,city,order_placed_time,order_delivered_time,delivery_minutes,distance_km,promised_sla_minutes,breached,day_of_week,hour_of_day
0,ORD-000001,STR-001,Jalandhar,2026-06-01 08:26:58,2026-06-01 08:37:11.200,10.22,0.81,10,True,Monday,8
1,ORD-000002,STR-001,Jalandhar,2026-06-01 15:51:56,2026-06-01 16:00:47.000,8.85,0.26,10,False,Monday,15
2,ORD-000003,STR-001,Jalandhar,2026-06-01 11:38:17,2026-06-01 11:49:51.200,11.57,3.77,10,True,Monday,11
3,ORD-000004,STR-001,Jalandhar,2026-06-01 10:19:27,2026-06-01 10:30:36.000,11.15,0.90,10,True,Monday,10
4,ORD-000005,STR-001,Jalandhar,2026-06-01 17:46:34,2026-06-01 17:56:09.400,9.59,3.08,10,False,Monday,17

In [11]:
df['is_weekend'] = df['day_of_week'].isin(
    ['Saturday', 'Sunday']
).astype(int)

In [13]:
X = pd.get_dummies(
    df[['store_id', 'hour_of_day', 'is_weekend', 'distance_km']],
    columns=['store_id']
)

y = df['breached']
X.head()

,hour_of_day,is_weekend,distance_km,store_id_STR-001,store_id_STR-002,store_id_STR-003,store_id_STR-004,store_id_STR-005,store_id_STR-006,store_id_STR-007,store_id_STR-008,store_id_STR-009,store_id_STR-010,store_id_STR-011,store_id_STR-012
0,8,0,0.81,True,False,False,False,False,False,False,False,False,False,False,False
1,15,0,0.26,True,False,False,False,False,False,False,False,False,False,False,False
2,11,0,3.77,True,False,False,False,False,False,False,False,False,False,False,False
3,10,0,0.90,True,False,False,False,False,False,False,False,False,False,False,False
4,17,0,3.08,True,False,False,False,False,False,False,False,False,False,False,False

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [15]:
print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (39955, 15)
Testing data: (9989, 15)

# train the random forest model

In [16]:
model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [18]:
print(classification_report(y_test, model.predict(X_test)))

              precision    recall  f1-score   support

       False       0.86      0.85      0.86      5870
        True       0.79      0.81      0.80      4119

    accuracy                           0.83      9989
   macro avg       0.83      0.83      0.83      9989
weighted avg       0.83      0.83      0.83      9989

In [19]:
importances = pd.Series(
    model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

importances.head(10)

distance_km         0.359876
hour_of_day         0.216266
store_id_STR-002    0.120210
store_id_STR-003    0.095383
store_id_STR-001    0.044233
store_id_STR-009    0.034092
store_id_STR-010    0.033949
store_id_STR-011    0.028402
store_id_STR-012    0.023476
store_id_STR-006    0.010466
dtype: float64

In [20]:
importances = pd.Series(
    model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

importances.head(10)

distance_km         0.359876
hour_of_day         0.216266
store_id_STR-002    0.120210
store_id_STR-003    0.095383
store_id_STR-001    0.044233
store_id_STR-009    0.034092
store_id_STR-010    0.033949
store_id_STR-011    0.028402
store_id_STR-012    0.023476
store_id_STR-006    0.010466
dtype: float64

## Load data and rank stores by breach rate

In [22]:
store_breach_pct = (
    df.groupby('store_id')['breached']
      .mean()
      .mul(100)
      .sort_values(ascending=False)
)

print(store_breach_pct)

store_id
STR-002    96.226852
STR-003    90.617520
STR-001    73.258049
STR-006    49.303829
STR-007    46.299856
STR-004    42.327273
STR-008    32.895040
STR-005    26.152702
STR-012    12.633579
STR-011     9.469328
STR-010     8.028306
STR-009     7.328718
Name: breached, dtype: float64

In [ ]:
## “I segmented stores into performance tiers based on their historical SLA breach rates.
    | Breach rate | Category         | Meaning                    |
| ----------- | ---------------- | -------------------------- |
| **> 60%**   | Chronic Breacher | Frequently missing the SLA |
| **20%–60%** | Average          | Moderate breach level      |
| **≤ 20%**   | Strong Performer | Usually meeting the SLA    |
”

In [23]:
def tier(rate):
    if rate > 0.6:
        return 'Chronic Breacher'
    elif rate > 0.2:
        return 'Average'
    else:
        return 'Strong Performer'

store_tiers = store_breach.apply(tier)

print(store_tiers)

store_id
STR-002    Chronic Breacher
STR-003    Chronic Breacher
STR-001    Chronic Breacher
STR-006             Average
STR-007             Average
STR-004             Average
STR-008             Average
STR-005             Average
STR-012    Strong Performer
STR-011    Strong Performer
STR-010    Strong Performer
STR-009    Strong Performer
Name: breached, dtype: object

In [24]:
df['tier'] = df['store_id'].map(store_tiers)

df.groupby('tier')[['distance_km', 'delivery_minutes']].mean()

                  distance_km  delivery_minutes
tier
Average              1.413235          9.589394
Chronic Breacher     1.384599         12.279007
Strong Performer     1.392749          7.217642

In [25]:
df['tier'] = df['store_id'].map(store_tiers)

## Check hour-by-hour pattern per tier

In [26]:
df.groupby(['tier', 'hour_of_day'])['breached'].mean().unstack().T

tier          Average  Chronic Breacher  Strong Performer
hour_of_day
8            0.183422          0.795252          0.013015
9            0.193662          0.753463          0.002294
10           0.175901          0.819074          0.007592
11           0.167273          0.782857          0.006818
12           0.179919          0.802554          0.008442
13           0.804309          0.992764          0.245385
14           0.798380          0.992958          0.248941
15           0.167442          0.789790          0.011834
16           0.183618          0.802038          0.005382
17           0.165593          0.809023          0.008919
18           0.174584          0.809524          0.003679
19           0.170096          0.807185          0.009029
20           0.778616          0.996369          0.241648
21           0.806413          0.988878          0.254690
22           0.810626          0.997063          0.255580
23           0.152542          0.807580          0.004773

## The analysis suggests that high SLA breach rates are not explained by delivery distance or order volume alone. Persistent breaches across different hours indicate that store-level operational factors may also need investigation, such as staffing, preparation processes, or rider allocation.

In [27]:
df.groupby('tier')['order_id'].count()

tier
Average             20678
Chronic Breacher    12660
Strong Performer    16606
Name: order_id, dtype: int64

### Key Findings & Recommendation

STR-002, STR-003, and STR-001 show consistently high SLA breach rates compared with other stores. Their average distance and order volume do not appear sufficient to explain the high breach rates. Breaches also remain high during off-peak hours, suggesting that the issue may be related to store-level operational factors rather than demand or distance alone. These locations should be investigated for factors such as staffing, order preparation time, fulfillment processes, and rider allocation.